version: 2
registries:
  d2l-private-npm:
    type: npm-registry
    url: https://d2l-569998014834.d.codeartifact.us-east-1.amazonaws.com/npm/private/
    token: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries: "*"
    schedule:
      interval: "daily"
