language: node_js
node_js: node
addons:
  chrome: stable
jobs:
  include:
  - stage: code-tests
    script:
    - npm run lint
    - |
      if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
        echo "Pull request with secure environment variables, running Sauce tests...";
        npm run test:sauce || travis_terminate 1;
      else
        echo "Not a pull request and/or no secure environment variables, running headless tests...";
        npm run test:headless || travis_terminate 1;
      fi
  - stage: visual-difference-tests
    script:
    - |
      if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
        echo "Running visual difference tests...";
        npm run test:diff || travis_terminate 1;
      fi
  - stage: update-version
    script: frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)

deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: BqP7PUmV5/SsQFaB6rtnx/yLizdJ7JRLGtUDS8RMsmMHl3s28srrRl10o30f6B55nHIONfujYddWjGJQCI1qjUNcrrB5dDs5QZ4ufYb0v0KwmhMGhOxgNyZqOkEyZ0SwR5jari5s4IS5xoG2UoEWEj0V/ij4OPj+KWpV6uxDWY+NCsc2+Ew3HoZA2lopOcr6N+iKDov4HcVZdwh51rNH9aG8XFHBMagndO5PP1lbovlP7/rQGBolgXjFIDvrI36YabxeUz7zofB2XnVJE7kDnCD4yig+kGmDNIWW1iHJb3YRlWuoeYgCvVBpliuRY2lQdPfJt5Q4xL5rJVw7drndT4FbVfa7ysKcNspsfcB3icVooXLjJGsnIAO96JjqPl56QKsYhEf3U2NQSXnekC1skE/SUy3HT781imiLC9oc/3R9pCA/YkJBlPJ7LFyef+p7QecTYGDPccH2n0s8iudv/0MHkU/wqL/3DkGk38UC9lNYoxAH5ddea1fvxbEBs8Gc40B0S+Vh9K0YO8z0qEbpjz4BjonCxpZ9YCJ2WX1JoFEZaFCRV0+TVdZa8Mq5zgwhTuPpXtpI52RbSoRo5Zrt/2RCEgvk9UgIc3E+OWatblLmw5uNREdN32ZwODMsQEaX2TVRRoEaQVdL9GIItWQ0RJ8kscs5Me05DreQgsR1MDQ=
  on:
    tags: true
    repo: BrightspaceUILabs/grade-result
env:
  global: 
  - SAUCE_USERNAME: Desire2Learn
  - OWNER_NAME: BrightspaceUILabs
  - REPO_NAME: grade-result
  - DEFAULT_INCREMENT: patch
  # GITHUB_RELEASE_TOKEN
  - secure: EvN853Xz+DgRYDPqkrFPODmNmO1JBTErtqRwMmC2MrJpvxOdT7YWxj16J7ZGIR9BXHhGtfugfFtSIQVPuemNAGvNCvTLxA8TgjtBIEECJFZKOIlWaDsCZn5c55xCx7EqPCdD/kIXQWEiatuARERug3hqG7ZyR4dD4qQfBh6XNAxkCOMfVRftx58j/bL6POwHltyiD7k0lMfDOnLnJKemzBp4saFNJloCwFHztwVyS5NO0WibaTaseT6VX7wUO5hGZ0zQdX+e/rt8Bi6icA8d5kb/CG/NcrIQdmfr+X47uieWiJw8X8+lzFJ2WFhnNh2GRP4ygiLVET3xygqPtEkUCms/y3Q2bwM3/ds5tmhBoP6AhC7+cw2t4hl01Ll2YM+xgNmMnfLxbz3sz6QqpLBCC5x0LfMk+m33zmtP+xakB18710HhI9IGvscm4cA2lo3Za95QycJq8sUaJ8PXi1cYTdd5kJldPdxUHNgM0lTZO8htP+bqNq+/1YzpWCAmfDj22cj+C44ZsYpqEa0O8RM2hHY4GlLuAkktBFLNihpzz+QGcCuBsbwMLUXj35OxwiWMmAm4KQBv4CC1bpNebNhLvzhH7rqSe3/eLVUrXLSPWoRynpdWLpU43E0fZ1kKpohm3XIjn49V3i65niH6J/p+N3swZ1fTkTqFJdo9PYsWJc8=
  # VISUAL_DIFF_S3_ID
  - secure: TCXsQPMA8oPjC6L42hVDiFyE+g6aCP+LJee823OAYiGQReXgI8hsUhAlBHf9gaZydi3OeuatQi+lGUxSdGS93dXPKD1RRjyG/7e5+txhrRmFpUr91/W+t9OkamEp7zMY7OwDGA/JBotO8hDwhlVLT2u6KP1Kv9qWndXNaZVKLWEc6n8rBIdXRJC6/wXTAwm7Hk/vmDq67wU0y+Lc4Hwnzo757Tujj3GvFdSIsZZWpB8tK9JukRGdfBgVHV5kaceNsWqnmqVuz8ea+dXpctrlEA5SbCwsxtWyyPCLknq2/ijOy9G1jUgd1I2PuElayHHIHmlaG7fnGF9Gp12bmqsNgJWmuhINQ/qxSlJs4Hu4F8etCpwTkS8qaaVjJuiY7+vmLtzDebwuuAjoIxENTksG3gLmnSD1TzvJ3N+NgyMN5LZvs38G+LpalR9snkJxaCRCeO4rru4uehxuNde90z88EXMJ96MBoDCJ/qgOkyPPQ+hKTmNOcLBQaZSia1hBbdjEbGZHoA8Cc/0f4fn0NfFw2fbVjZ8bJJ3SnDejTJozSE4gBG/ouHrNFj8NqEy7I+N2ufLOxatvkTSmDqdo+fql+SxjVNWAIazwbnHrOKbEJOUJNCzFCvaFl7bji8pqxD3CMHch/R3S+epwReNVUBpRW6kHRhj8BRZKgkm+2zAOXuY=
  # VISUAL_DIFF_S3_SECRET
  - secure: OQOybsTlO+n0mSpWXCQ2+0eHTadjpgikxCMQYe+k2GKdxlZvE3tLymeEfGiKX6XbUF6ii1+wvGGCmH3FkycwVqUVc+55prTx94gKX9WNHoB+aRbuW0IG0TuZ8T4M6EbL1LzgHYb3sJPOWa5q/IwePuiNxUpVnydNNAiB2GhrCZn/T/fnw10IOjG40JKaUh8hsBkw+DEB9OGs0ckgvVc8F+dciAQpDv2kBn1JwsjY5SYd4k9SrmE5w+x5UgacwwTE76zwOCy7Cm29xDV7+wc2Mb6dPCCwDbgQbj0p+ghfqOIORv07MKQrALLH/IA11jhdgvsa2pxCplAPbEMU5WrSGQDdN06RQSGeHZQ2CkczXrC6G77IcfvBvpagQ2jzXLa7nk5nXpq26BzH/8176vN2uMNiWjfROxUBFwzoO2q6fm8Sd8XAdTViPSuXrXuT2SmNOf8o7lID/C/nxhi5ih5n/WVGhyZAmODdB5Wm7jzCieJVykjZI0pZ5DS1/gSQvHUbvZNyV8qcUvAFixLVdCHi3zox28LrAb2GrlhbPO9YWOZx1bEnG03y/vYJJ7Tgigomd/2nTii+D1fzBrR+sUpNDcAqXTbH2Ylav5gd3EHQY614ILXb3hCr3JEQIVKJchIGMxW5/RC3SnvT+TsJr5z5JuqVbpqGre6qLWlrI8Jizbg=
  # SAUCE_ACCESS_KEY
  - secure: mVlkTi17S8oZ8rJIQ/7a180UQwJHSz4kbaWLJL9WW/EmhAAQPWoEx75beOtgRT5atEr/iPtqytzTU8KdCgJBZ7/gJJ7NQWvwUlEQNEom4f+2xIXrjTdXNPWWd0LduqvSBAvm+lk1W3rBapR6f9RzWE/ErjPJrtvbAdosNFVZD8WLqq/ID2WHHITb3/lYxg7gQUxLPBgVeZxHHlYn4IlalW5+CPb7OAhOiVfKd3Os9Phv/NbyDuYSzOxQgzYqWl9X037IV7izHTZDdsoM0o2DjoJ+8VzQ7+ul8YUWF3kHRPK9/HmkCD3cLe6HiDFZO7ubpm5pn4fXDoKpWL5DBgUWgRDg767AQQvnEKvWs67G8LZdQIFmkBEZErTq66fXqwrOK/Gct7uav1Egun7admlS4QjWNvTSxesuNwozI+uzrY5Cj8EAYhORvOGRz1MVyTwCJLuUE6MGfukwXBbSjdObFbYb0GrmY2cNUvWmYr0wfdAE0hFzLv0RlVJ4zU3xmGUoeJliqduG587oIge/TWXq4mm+9B+hUqiyXeUr+evnpv6VxHotmhKujnIhMgOSNISPz3k9JozN9GluBX6jXP+GApcNgLytHX/lnwfG+a1L/apAU4UbfL1dH+eXXat8x84xlNIK/G2oMc+4rueLUe5cgBtYeTfUmYZcdYK00L97ExE=
