name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint (JavaScript)
        run: npm run lint:eslint
      - name: Lint (CSS)
        run: npm run lint:style
      - name: Validate Translations
        run: npm run test:translations
      - name: Accessibility Tests
        id: at
        run: npm run test:axe
      - name: Upload test report
        if: >
          always() &&
          github.triggering_actor != 'dependabot[bot]' &&
          (steps.at.outcome == 'failure' || steps.at.outcome == 'success')
        uses: Brightspace/test-reporting-action@main
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
      - name: Unit Tests
        id: ut
        run: npm run test:unit
      - name: Upload test report
        if: >
          always() &&
          github.triggering_actor != 'dependabot[bot]' &&
          (steps.ut.outcome == 'failure' || steps.ut.outcome == 'success')
        uses: Brightspace/test-reporting-action@main
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
