name: D2L-Router
on: pull_request
jobs:

  lint:
    timeout-minutes: 5
    runs-on: [self-hosted, AWS, Linux]
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
  tests:
    timeout-minutes: 15
    runs-on: [self-hosted, AWS, Linux]
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Unit Tests (cross-browser)
        run: npm run test:headless:ci
