name: Release
on:
  push:
    branches: [main, 'release/**']
jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Match LMS Release
        uses: Brightspace/lms-version-actions/match-lms-release@main
        with:
          RALLY_API_KEY: ${{ secrets.RALLY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
